grails-app/controllers/org/bbop/apollo/FeatureTypeController.groovy
package org.bbop.apollo

import org.bbop.apollo.gwt.shared.PermissionEnum

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class FeatureTypeController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def permissionService

    def beforeInterceptor = {
        if(!permissionService.checkPermissions(PermissionEnum.ADMINISTRATE)){
            forward action: "notAuthorized" ,controller: "annotator"
            return
        }
    }

    def index(Integer max) {
        params.max = Math.min(max ?: 30, 200)
        respond FeatureType.list(params), model:[featureTypeInstanceCount: FeatureType.count()]
    }

    def show(FeatureType featureTypeInstance) {
        respond featureTypeInstance
    }

    def create() {
        respond new FeatureType(params)
    }

    @Transactional
    def save(FeatureType featureTypeInstance) {
        if (featureTypeInstance == null) {
            notFound()
            return
        }

        if (featureTypeInstance.hasErrors()) {
            respond featureTypeInstance.errors, view:'create'
            return
        }

        featureTypeInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'featureType.label', default: 'FeatureType'), featureTypeInstance.id])
                redirect featureTypeInstance
            }
            '*' { respond featureTypeInstance, [status: CREATED] }
        }
    }

    def edit(FeatureType featureTypeInstance) {
        respond featureTypeInstance
    }

    @Transactional
    def update(FeatureType featureTypeInstance) {
        if (featureTypeInstance == null) {
            notFound()
            return
        }

        if (featureTypeInstance.hasErrors()) {
            respond featureTypeInstance.errors, view:'edit'
            return
        }

        featureTypeInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'FeatureType.label', default: 'FeatureType'), featureTypeInstance.id])
                redirect featureTypeInstance
            }
            '*'{ respond featureTypeInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(FeatureType featureTypeInstance) {

        if (featureTypeInstance == null) {
            notFound()
            return
        }

        featureTypeInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'FeatureType.label', default: 'FeatureType'), featureTypeInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'featureType.label', default: 'FeatureType'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/featureType/_form.gsp
<%@ page import="org.bbop.apollo.FeatureType" %>



<div class="fieldcontain ${hasErrors(bean: featureTypeInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="featureType.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" required="" value="${featureTypeInstance?.name}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: featureTypeInstance, field: 'display', 'error')} required">
	<label for="display">
		<g:message code="featureType.display.label" default="Display" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="display" required="" value="${featureTypeInstance?.display}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: featureTypeInstance, field: 'ontologyId', 'error')} required">
	<label for="ontologyId">
		<g:message code="featureType.ontologyId.label" default="Ontology Id" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="ontologyId" required="" value="${featureTypeInstance?.ontologyId}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: featureTypeInstance, field: 'type', 'error')} required">
	<label for="type">
		<g:message code="featureType.type.label" default="Type" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="type" required="" value="${featureTypeInstance?.type}"/>

</div>

grails-app/views/featureType/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'featureType.label', default: 'FeatureType')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-featureType" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-featureType" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${featureTypeInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${featureTypeInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:featureTypeInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/featureType/edit.gsp
<%@ page import="org.bbop.apollo.FeatureType" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'featureType.label', default: 'FeatureType')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-featureType" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-featureType" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${featureTypeInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${featureTypeInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:featureTypeInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${featureTypeInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/featureType/index.gsp
<%@ page import="org.bbop.apollo.FeatureType" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'featureType.label', default: 'FeatureType')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-featureType" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-featureType" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'featureType.name.label', default: 'Name')}" />

						<g:sortableColumn property="display" title="${message(code: 'featureType.display.label', default: 'Display')}" />

						<g:sortableColumn property="ontologyId" title="${message(code: 'featureType.ontologyId.label', default: 'Ontology Id')}" />

						<g:sortableColumn property="type" title="${message(code: 'featureType.type.label', default: 'Type')}" />
						<th>Filter</th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${featureTypeInstanceList}" status="i" var="featureTypeInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${featureTypeInstance.id}">${fieldValue(bean: featureTypeInstance, field: "display")}</g:link></td>

						<td>${fieldValue(bean: featureTypeInstance, field: "display")}</td>
						<td>${fieldValue(bean: featureTypeInstance, field: "ontologyId")}</td>
						<td>${fieldValue(bean: featureTypeInstance, field: "type")}</td>

						<td>${fieldValue(bean: featureTypeInstance, field: "type")}:${featureTypeInstance.name}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${featureTypeInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/featureType/show.gsp
<%@ page import="org.bbop.apollo.FeatureType" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'featureType.label', default: 'FeatureType')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-featureType" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                  default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="show-featureType" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol class="property-list featureType">

        <li class="fieldcontain">
            <span id="name-label" class="property-label"><g:message code="featureType.name.label"
                                                                    default="Name"/></span>

            <span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${featureTypeInstance}"
                                                                                    field="name"/></span>

        </li>

        <li class="fieldcontain">
            <span id="display-label" class="property-label"><g:message code="featureType.display.label"
                                                                       default="Display"/></span>
            <span class="property-value" aria-labelledby="display-label"><g:fieldValue bean="${featureTypeInstance}"
                                                                                       field="display"/></span>
        </li>

        <li class="fieldcontain">
            <span id="ontologyId-label" class="property-label"><g:message code="featureType.ontologyId.label"
                                                                          default="Ontology Id"/></span>
            <span class="property-value" aria-labelledby="ontologyId-label"><g:fieldValue bean="${featureTypeInstance}"
                                                                                          field="ontologyId"/></span>
        </li>

        <li class="fieldcontain">
            <span id="type-label" class="property-label"><g:message code="featureType.type.label"
                                                                    default="Type"/></span>
            <span class="property-value" aria-labelledby="type-label"><g:fieldValue bean="${featureTypeInstance}"
                                                                                    field="type"/></span>
        </li>

    </ol>
    <g:form url="[resource: featureTypeInstance, action: 'delete']" method="DELETE">
        <fieldset class="buttons">
            <g:link class="edit" action="edit" resource="${featureTypeInstance}"><g:message
                    code="default.button.edit.label" default="Edit"/></g:link>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>