grails-app/domain/org/bbop/apollo/CannedKey.groovy
package org.bbop.apollo

class CannedKey {

    static constraints = {
        label nullable: false
        metadata nullable: true
    }

    String label
    String metadata

    static hasMany = [
        featureTypes: FeatureType
    ]
}

grails-app/controllers/org/bbop/apollo/CannedKeyController.groovy
package org.bbop.apollo


import grails.converters.JSON
import org.bbop.apollo.gwt.shared.FeatureStringEnum
import org.bbop.apollo.gwt.shared.GlobalPermissionEnum

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import org.bbop.apollo.gwt.shared.PermissionEnum
import org.codehaus.groovy.grails.web.json.JSONObject
import org.restapidoc.annotation.RestApi
import org.restapidoc.annotation.RestApiMethod
import org.restapidoc.annotation.RestApiParam
import org.restapidoc.annotation.RestApiParams
import org.restapidoc.pojo.RestApiParamType
import org.restapidoc.pojo.RestApiVerb

@RestApi(name = "Canned Keys Services", description = "Methods for managing canned keys")
@Transactional(readOnly = true)
class CannedKeyController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def permissionService

    def beforeInterceptor = {
        if(!permissionService.checkPermissions(PermissionEnum.ADMINISTRATE)){
            forward action: "notAuthorized", controller: "annotator"
            return
        }
    }

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)

        def cannedKeys = CannedKey.list(params)
        def organismFilterMap = [:]
        CannedKeyOrganismFilter.findAllByCannedKeyInList(cannedKeys).each() {
            List filterList = organismFilterMap.containsKey(it.cannedKey) ? organismFilterMap.get(it.cannedKey) : []
            filterList.add(it)
            organismFilterMap[it.cannedKey] = filterList
        }
        respond cannedKeys, model: [cannedKeyInstanceCount: CannedKey.count(), organismFilters: organismFilterMap]
    }

    def show(CannedKey cannedKeyInstance) {
        respond cannedKeyInstance, model: [organismFilters: CannedKeyOrganismFilter.findAllByCannedKey(cannedKeyInstance)]
    }

    def create() {
        respond new CannedKey(params)
    }

    @Transactional
    def save(CannedKey cannedKeyInstance) {
        if (cannedKeyInstance == null) {
            notFound()
            return
        }

        if (cannedKeyInstance.hasErrors()) {
            respond cannedKeyInstance.errors, view:'create'
            return
        }

        cannedKeyInstance.save()

        if (params.organisms instanceof String) {
            params.organisms = [params.organisms]
        }

        params?.organisms.each {
            Organism organism = Organism.findById(it)
            new CannedKeyOrganismFilter(
                    organism: organism,
                    cannedKey: cannedKeyInstance
            ).save()
        }

        cannedKeyInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'cannedKey.label', default: 'CannedKey'), cannedKeyInstance.id])
                redirect cannedKeyInstance
            }
            '*' { respond cannedKeyInstance, [status: CREATED] }
        }
    }

    def edit(CannedKey cannedKeyInstance) {
        respond cannedKeyInstance
    }

    @Transactional
    def update(CannedKey cannedKeyInstance) {
        if (cannedKeyInstance == null) {
            notFound()
            return
        }

        if (cannedKeyInstance.hasErrors()) {
            respond cannedKeyInstance.errors, view:'edit'
            return
        }

        cannedKeyInstance.save()

        CannedKeyOrganismFilter.deleteAll(CannedKeyOrganismFilter.findAllByCannedKey(cannedKeyInstance))

        if (params.organisms instanceof String) {
            params.organisms = [params.organisms]
        }

        params?.organisms.each {
            Organism organism = Organism.findById(it)
            new CannedKeyOrganismFilter(
                    organism: organism,
                    cannedKey: cannedKeyInstance
            ).save()
        }

        cannedKeyInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'CannedKey.label', default: 'CannedKey'), cannedKeyInstance.id])
                redirect cannedKeyInstance
            }
            '*'{ respond cannedKeyInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(CannedKey cannedKeyInstance) {

        if (cannedKeyInstance == null) {
            notFound()
            return
        }

        cannedKeyInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'CannedKey.label', default: 'CannedKey'), cannedKeyInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'cannedKey.label', default: 'CannedKey'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    @RestApiMethod(description = "Create canned key", path = "/cannedKey/createKey", verb = RestApiVerb.POST)
    @RestApiParams(params = [
            @RestApiParam(name = "username", type = "email", paramType = RestApiParamType.QUERY)
            , @RestApiParam(name = "password", type = "password", paramType = RestApiParamType.QUERY)
            , @RestApiParam(name = "key", type = "string", paramType = RestApiParamType.QUERY, description = "Canned key to add")
            , @RestApiParam(name = "metadata", type = "string", paramType = RestApiParamType.QUERY, description = "Optional additional information")
    ]
    )
    @Transactional
    def createKey() {
        JSONObject keyJson = permissionService.handleInput(request, params)
        try {
            if (permissionService.isUserGlobalAdmin(permissionService.getCurrentUser(keyJson))) {
                if (!keyJson.key) {
                    throw new Exception('empty fields detected')
                }

                if (!keyJson.metadata) {
                    keyJson.metadata = ""
                }

                log.debug "Adding canned key ${keyJson.key}"
                CannedKey key = new CannedKey(
                        label: keyJson.key,
                        metadata: keyJson.metadata
                ).save(flush: true)

                render key as JSON
            } else {
                def error = [error: 'not authorized to add CannedKey']
                render error as JSON
                log.error(error.error)
            }
        } catch (e) {
            def error = [error: 'problem saving CannedKey: ' + e]
            render error as JSON
            e.printStackTrace()
            log.error(error.error)
        }
    }

    @RestApiMethod(description = "Update canned key", path = "/cannedKey/updateKey", verb = RestApiVerb.POST)
    @RestApiParams(params = [
            @RestApiParam(name = "username", type = "email", paramType = RestApiParamType.QUERY)
            , @RestApiParam(name = "password", type = "password", paramType = RestApiParamType.QUERY)
            , @RestApiParam(name = "id", type = "long", paramType = RestApiParamType.QUERY, description = "Canned key ID to update (or specify the old_key)")
            , @RestApiParam(name = "old_key", type = "string", paramType = RestApiParamType.QUERY, description = "Canned key to update")
            , @RestApiParam(name = "new_key", type = "string", paramType = RestApiParamType.QUERY, description = "Canned key to change to (the only editable option)")
            , @RestApiParam(name = "metadata", type = "string", paramType = RestApiParamType.QUERY, description = "Optional additional information")
    ]
    )
    @Transactional
    def updateKey() {
        try {
            JSONObject keyJson = permissionService.handleInput(request, params)
            log.debug "Updating canned key ${keyJson}"
            if (permissionService.isUserGlobalAdmin(permissionService.getCurrentUser(keyJson))) {

                log.debug "Canned key ID: ${keyJson.id}"
                CannedKey key = CannedKey.findById(keyJson.id) ?: CannedKey.findByLabel(keyJson.old_key)

                if (!key) {
                    JSONObject jsonObject = new JSONObject()
                    jsonObject.put(FeatureStringEnum.ERROR.value, "Failed to update the canned key")
                    render jsonObject as JSON
                    return
                }

                key.label = keyJson.new_key

                if (keyJson.metadata) {
                    key.metadata = keyJson.metadata
                }

                key.save(flush: true)

                log.info "Success updating canned key: ${key.id}"
                render new JSONObject() as JSON
            } else {
                def error = [error: 'not authorized to edit canned key']
                log.error(error.error)
                render error as JSON
            }
        }
        catch (Exception e) {
            def error = [error: 'problem editing canned key: ' + e]
            log.error(error.error)
            render error as JSON
        }
    }

    @RestApiMethod(description = "Remove a canned key", path = "/cannedKey/deleteKey", verb = RestApiVerb.POST)
    @RestApiParams(params = [
            @RestApiParam(name = "username", type = "email", paramType = RestApiParamType.QUERY)
            , @RestApiParam(name = "password", type = "password", paramType = RestApiParamType.QUERY)
            , @RestApiParam(name = "id", type = "long", paramType = RestApiParamType.QUERY, description = "Canned key ID to remove (or specify the name)")
            , @RestApiParam(name = "key", type = "string", paramType = RestApiParamType.QUERY, description = "Canned key to delete")
    ])
    @Transactional

grails-app/views/cannedKey/_form.gsp
<%@ page import="org.bbop.apollo.CannedKey" %>



<div class="fieldcontain ${hasErrors(bean: cannedKeyInstance, field: 'label', 'error')} required">
    <label for="label">
        <g:message code="cannedKey.label.label" default="Label"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="label" required="" value="${cannedKeyInstance?.label}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: cannedKeyInstance, field: 'metadata', 'error')} ">
    <label for="metadata">
        <g:message code="cannedKey.metadata.label" default="Metadata"/>

    </label>
    <g:textField name="metadata" value="${cannedKeyInstance?.metadata}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: cannedKeyInstance, field: 'featureTypes', 'error')} ">
    <label for="featureTypes">
        <g:message code="cannedKey.featureTypes.label" default="Feature Types"/>

    </label>
    <g:select name="featureTypes" from="${org.bbop.apollo.FeatureType.list()}" multiple="multiple" optionKey="id"
              size="10" value="${cannedKeyInstance?.featureTypes*.id}" class="many-to-many" optionValue="display"/>

</div>

<div class="fieldcontain ${hasErrors(bean: cannedKeyInstance, field: 'organisms', 'error')} ">
    <label for="organisms">
        <g:message code="cannedKey.organisms.label" default="Organisms" />

    </label>
    <g:select name="organisms" from="${org.bbop.apollo.Organism.list()}"
              multiple="multiple"
              optionKey="id" size="10"
              optionValue="commonName"
              value="${organismFilters?.organism?.id}" class="many-to-many"/>

</div>

grails-app/views/cannedKey/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'cannedKey.label', default: 'CannedKey')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-cannedKey" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-cannedKey" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${cannedKeyInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${cannedKeyInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:cannedKeyInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/cannedKey/edit.gsp
<%@ page import="org.bbop.apollo.CannedKey" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'cannedKey.label', default: 'CannedKey')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-cannedKey" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-cannedKey" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${cannedKeyInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${cannedKeyInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:cannedKeyInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${cannedKeyInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/cannedKey/index.gsp
<%@ page import="org.bbop.apollo.CannedKey" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'cannedKey.label', default: 'CannedKey')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-cannedKey" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-cannedKey" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="label" title="${message(code: 'cannedKey.label.label', default: 'Label')}" />
						<th>Feature Types</th>
						<th>Organisms</th>

						<g:sortableColumn property="metadata" title="${message(code: 'cannedKey.metadata.label', default: 'Metadata')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${cannedKeyInstanceList}" status="i" var="cannedKeyInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${cannedKeyInstance.id}">${fieldValue(bean: cannedKeyInstance, field: "label")}</g:link></td>

						<td>
							<g:each in="${cannedKeyInstance.featureTypes.sort() { a,b -> a.display <=> b.display }}" var="featureType">
								${featureType.type}:${featureType.name}
							</g:each>
						</td>
						<td>
							<g:each in="${organismFilters.get(cannedKeyInstance)}" var="filter">
								<g:link controller="organism" id="${filter.organism.id}">${filter.organism.commonName}</g:link>
							</g:each>
						</td>

						<td>${fieldValue(bean: cannedKeyInstance, field: "metadata")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${cannedKeyInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/cannedKey/show.gsp
<%@ page import="org.bbop.apollo.CannedKey" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'cannedKey.label', default: 'CannedKey')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-cannedKey" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="show-cannedKey" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol class="property-list cannedKey">

        <g:if test="${cannedKeyInstance?.label}">
            <li class="fieldcontain">
                <span id="label-label" class="property-label"><g:message code="cannedKey.label.label"
                                                                         default="Label"/></span>

                <span class="property-value" aria-labelledby="label-label"><g:fieldValue bean="${cannedKeyInstance}"
                                                                                         field="label"/></span>

            </li>
        </g:if>

        <g:if test="${cannedKeyInstance?.metadata}">
            <li class="fieldcontain">
                <span id="metadata-label" class="property-label"><g:message code="cannedKey.metadata.label"
                                                                            default="Metadata"/></span>

                <span class="property-value" aria-labelledby="metadata-label"><g:fieldValue bean="${cannedKeyInstance}"
                                                                                            field="metadata"/></span>

            </li>
        </g:if>

        <g:if test="${cannedKeyInstance?.featureTypes}">
            <li class="fieldcontain">
                <span id="featureTypes-label" class="property-label"><g:message code="cannedKey.featureTypes.label"
                                                                                default="Feature Types"/></span>

                <g:each in="${cannedKeyInstance.featureTypes}" var="f">
                    <span class="property-value" aria-labelledby="featureTypes-label"><g:link controller="featureType"
                                                                                              action="show"
                                                                                              id="${f.id}">${f?.display}</g:link></span>
                </g:each>

            </li>
        </g:if>

        <g:if test="${organismFilters}">
            <li class="fieldcontain">
                <span id="organisms-label" class="property-label"><g:message code="cannedKey.organisms.label"
                                                                             default="Organisms"/></span>

                <g:each in="${organismFilters}" var="f">
                    <span class="property-value" aria-labelledby="organisms-label"><g:link controller="organism"
                                                                                           action="show"
                                                                                           id="${f.id}">${f?.organism.commonName}</g:link></span>
                </g:each>
            </li>
        </g:if>

    %{--<g:if test="${cannedKeyInstance?.values}">--}%
    %{--<li class="fieldcontain">--}%
    %{--<span id="values-label" class="property-label"><g:message code="cannedKey.values.label" default="Values" /></span>--}%
    %{----}%
    %{--<g:each in="${cannedKeyInstance.values}" var="v">--}%
    %{--<span class="property-value" aria-labelledby="values-label"><g:link controller="cannedValue" action="show" id="${v.id}">${v?.label}</g:link></span>--}%
    %{--</g:each>--}%
    %{----}%
    %{--</li>--}%
    %{--</g:if>--}%

    </ol>
    <g:form url="[resource: cannedKeyInstance, action: 'delete']" method="DELETE">
        <fieldset class="buttons">
            <g:link class="edit" action="edit" resource="${cannedKeyInstance}"><g:message
                    code="default.button.edit.label" default="Edit"/></g:link>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>