grails-app/domain/org/bbop/apollo/Proxy.groovy
package org.bbop.apollo

class Proxy {

    static constraints = {
        fallbackOrder nullable: true
        lastSuccess nullable: true
        lastFail nullable: true
        referenceUrl url: true, nullable: false,blank: false
        targetUrl url: true, nullable: false,blank: false
        active nullable: false
    }

    static mapping= {
        active defaultValue: true
    }

    String referenceUrl
    String targetUrl
    Boolean active
    Integer fallbackOrder
    Date lastSuccess
    Date lastFail
}

grails-app/controllers/org/bbop/apollo/ProxyController.groovy
package org.bbop.apollo

import grails.transaction.Transactional
import org.bbop.apollo.gwt.shared.PermissionEnum

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class ProxyController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def permissionService
    def proxyService

    def beforeInterceptor = {
        if (actionName != "request" && !permissionService.checkPermissions(PermissionEnum.ADMINISTRATE)) {
            forward action: "notAuthorized", controller: "annotator"
            return
        }
    }

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Proxy.list(params), model: [proxyInstanceCount: Proxy.count()]
    }

    def show(Proxy proxyInstance) {
        respond proxyInstance
    }

    def create() {
        params.active = true
        respond new Proxy(params)
    }

    /**
     * @return
     */
    @Transactional
    def request(String url) {
        // only a logged-in user can use the proxy
        User currentUser = permissionService.currentUser
        if (!currentUser) {
            log.warn "Attempting to proxy ${url} without a logged-in user"
            render status: UNAUTHORIZED
            return
        }
        String referenceUrl = URLDecoder.decode(url, "UTF-8")
        Proxy proxy = proxyService.findProxyForUrl(referenceUrl)


        if (!proxy) {
            log.error "Proxy not found for ${referenceUrl}.  Please add a proxy (see the config guide)."
            render status: NOT_FOUND
            return
        }

        log.info "using proxy ${proxy?.targetUrl}"

        String targetUrl = proxy ? proxy.targetUrl : referenceUrl

        targetUrl += "?" + request.queryString
        log.debug "target url: ${targetUrl}"
        URL returnUrl = new URL(targetUrl)

        log.debug "input URI ${request.requestURI}"
        log.info "request url ${referenceUrl}?${request.getQueryString()}"
        log.info "return url: ${returnUrl}"
        render text: returnUrl.text
    }


    @Transactional
    def save(Proxy proxyInstance) {
        if (proxyInstance == null) {
            notFound()
            return
        }

        if (proxyInstance.hasErrors()) {
            respond proxyInstance.errors, view: 'create'
            return
        }

        proxyInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'proxy.label', default: 'Proxy'), proxyInstance.id])
                redirect proxyInstance
            }
            '*' { respond proxyInstance, [status: CREATED] }
        }
    }

    def edit(Proxy proxyInstance) {
        respond proxyInstance
    }

    @Transactional
    def update(Proxy proxyInstance) {
        if (proxyInstance == null) {
            notFound()
            return
        }

        if (proxyInstance.hasErrors()) {
            respond proxyInstance.errors, view: 'edit'
            return
        }

        proxyInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Proxy.label', default: 'Proxy'), proxyInstance.id])
                redirect proxyInstance
            }
            '*' { respond proxyInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Proxy proxyInstance) {

        if (proxyInstance == null) {
            notFound()
            return
        }

        proxyInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Proxy.label', default: 'Proxy'), proxyInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'proxy.label', default: 'Proxy'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/proxy/_form.gsp
<%@ page import="org.bbop.apollo.Proxy" %>


<div class="fieldcontain ${hasErrors(bean: proxyInstance, field: 'referenceUrl', 'error')} required">
	<label for="referenceUrl">
		<g:message code="proxy.referenceUrl.label" default="Reference Url" />
		<span class="required-indicator">*</span>
	</label>
	<g:field type="url" name="referenceUrl" required="" value="${proxyInstance?.referenceUrl}" size="80"/>

</div>

<div class="fieldcontain ${hasErrors(bean: proxyInstance, field: 'targetUrl', 'error')} required">
	<label for="targetUrl">
		<g:message code="proxy.targetUrl.label" default="Target Url" />
		<span class="required-indicator">*</span>
	</label>
	<g:field type="url" name="targetUrl" required="" value="${proxyInstance?.targetUrl}" size="80"/>

</div>

<div class="fieldcontain ${hasErrors(bean: proxyInstance, field: 'active', 'error')} ">
	<label for="active">
		<g:message code="proxy.active.label" default="Active" />

	</label>
	<g:checkBox name="active" value="${proxyInstance?.active}" />

</div>


<div class="fieldcontain ${hasErrors(bean: proxyInstance, field: 'fallbackOrder', 'error')} ">
	<label for="fallbackOrder">
		<g:message code="proxy.fallbackOrder.label" default="Fallback Order" />
		
	</label>
	<g:field name="fallbackOrder" type="number" value="${proxyInstance.fallbackOrder}"/>

</div>

<br/>

grails-app/views/proxy/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'proxy.label', default: 'Proxy')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-proxy" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-proxy" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${proxyInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${proxyInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:proxyInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/proxy/edit.gsp
<%@ page import="org.bbop.apollo.Proxy" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'proxy.label', default: 'Proxy')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-proxy" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-proxy" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${proxyInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${proxyInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:proxyInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${proxyInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/proxy/index.gsp
<%@ page import="org.bbop.apollo.Proxy" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'proxy.label', default: 'Proxy')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-proxy" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-proxy" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
						<th></th>
						<g:sortableColumn property="referenceUrl" title="${message(code: 'proxy.referenceUrl.label', default: 'Reference Url')}" />

						<g:sortableColumn property="targetUrl" title="${message(code: 'proxy.targetUrl.label', default: 'Target Url')}" />

						<g:sortableColumn property="active" title="${message(code: 'proxy.active.label', default: 'Active')}" />

						<g:sortableColumn property="fallbackOrder" title="${message(code: 'proxy.fallbackOrder.label', default: 'Fallback Order')}" />
					
						<g:sortableColumn property="lastSuccess" title="${message(code: 'proxy.lastSuccess.label', default: 'Last Success')}" />
					
						<g:sortableColumn property="lastFail" title="${message(code: 'proxy.lastFail.label', default: 'Last Fail')}" />
					

					</tr>
				</thead>
				<tbody>
				<g:each in="${proxyInstanceList}" status="i" var="proxyInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">


						<td>
							<g:link action="show" id="${proxyInstance.id}">Show</g:link>
						</td>

						<td>${fieldValue(bean: proxyInstance, field: "referenceUrl")}</td>

						<td>${fieldValue(bean: proxyInstance, field: "targetUrl")}</td>

						<td><g:formatBoolean boolean="${proxyInstance.active}" /></td>

						<td>${fieldValue(bean: proxyInstance, field: "fallbackOrder")}</td>
					
						<td><g:formatDate date="${proxyInstance.lastSuccess}" /></td>
					
						<td><g:formatDate date="${proxyInstance.lastFail}" /></td>
					

					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${proxyInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/proxy/show.gsp
<%@ page import="org.bbop.apollo.Proxy" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'proxy.label', default: 'Proxy')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-proxy" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-proxy" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list proxy">

				<li class="fieldcontain">
					<span id="referenceUrl-label" class="property-label"><g:message code="proxy.referenceUrl.label" default="Reference Url" /></span>

					<span class="property-value" aria-labelledby="referenceUrl-label"><g:fieldValue bean="${proxyInstance}" field="referenceUrl"/></span>

				</li>
				<li class="fieldcontain">
					<span id="targetUrl-label" class="property-label"><g:message code="proxy.targetUrl.label" default="Target Url" /></span>

					<span class="property-value" aria-labelledby="targetUrl-label"><g:fieldValue bean="${proxyInstance}" field="targetUrl"/></span>

				</li>

				<li class="fieldcontain">
					<span id="active-label" class="property-label"><g:message code="proxy.active.label" default="Active" /></span>

					<span class="property-value" aria-labelledby="active-label"><g:formatBoolean boolean="${proxyInstance?.active}" /></span>

				</li>

				%{--<g:if test="${proxyInstance?.fallbackOrder}">--}%
				<li class="fieldcontain">
					<span id="fallbackOrder-label" class="property-label"><g:message code="proxy.fallbackOrder.label" default="Fallback Order" /></span>
						<span class="property-value" aria-labelledby="fallbackOrder-label"><g:fieldValue bean="${proxyInstance}" field="fallbackOrder"/></span>
					
				</li>
				%{--</g:if>--}%
			
				%{--<g:if test="${proxyInstance?.lastSuccess}">--}%
				%{--<li class="fieldcontain">--}%
					%{--<span id="lastSuccess-label" class="property-label"><g:message code="proxy.lastSuccess.label" default="Last Success" /></span>--}%
					%{----}%
						%{--<span class="property-value" aria-labelledby="lastSuccess-label"><g:formatDate date="${proxyInstance?.lastSuccess}" /></span>--}%
					%{----}%
				%{--</li>--}%
				%{--</g:if>--}%
			
				%{--<g:if test="${proxyInstance?.lastFail}">--}%
				%{--<li class="fieldcontain">--}%
					%{--<span id="lastFail-label" class="property-label"><g:message code="proxy.lastFail.label" default="Last Fail" /></span>--}%
					%{----}%
						%{--<span class="property-value" aria-labelledby="lastFail-label"><g:formatDate date="${proxyInstance?.lastFail}" /></span>--}%
					%{----}%
				%{--</li>--}%
				%{--</g:if>--}%
			

			</ol>
			<g:form url="[resource:proxyInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${proxyInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>